name: Build and Release Windows

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Allows manual triggering

# Add permissions for the workflow
permissions:
  contents: write  # Needed to create releases and upload assets
  actions: read    # Needed to download artifacts

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller main.spec

    - name: Prepare executable
      run: |
        move dist\HelloWorldApp.exe HelloWorldApp.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: HelloWorldApp.exe
        path: HelloWorldApp.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: HelloWorldApp.exe

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: HelloWorldApp.exe
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}